name: default-pipe
input:
  - name: stdin-input
    kind: stdin
    codec:
      kind: json
    value1: true
    value2: asdf
    value3: 222
output:
  - name: stdout-output
    kind: stdout
    cond:
      - add_tag: xxx
    codec:
      kind: json

